/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import conexionSQL.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Fases extends javax.swing.JFrame {

    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();
    
    public Fases() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIdF = new javax.swing.JLabel();
        lblNomF = new javax.swing.JLabel();
        btnNuevaF = new javax.swing.JButton();
        btnListarF = new javax.swing.JButton();
        btnActualizarF = new javax.swing.JButton();
        btnEliminarF = new javax.swing.JButton();
        btnGuardarF = new javax.swing.JButton();
        txtIdF = new javax.swing.JTextField();
        txtNomF = new javax.swing.JTextField();
        btnRF = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaFases = new javax.swing.JTable();
        lblBuscar = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fases");

        lblIdF.setText("Id:");

        lblNomF.setText("Nombre:");

        btnNuevaF.setText("Nuevo");
        btnNuevaF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaFActionPerformed(evt);
            }
        });

        btnListarF.setText("Listar");
        btnListarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarFActionPerformed(evt);
            }
        });

        btnActualizarF.setText("Actualizar");
        btnActualizarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarFActionPerformed(evt);
            }
        });

        btnEliminarF.setText("Eliminar");
        btnEliminarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarFActionPerformed(evt);
            }
        });

        btnGuardarF.setText("Guardar");
        btnGuardarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarFActionPerformed(evt);
            }
        });

        btnRF.setForeground(new java.awt.Color(204, 0, 0));
        btnRF.setText("Regresar");
        btnRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnNuevaF)
                        .addGap(27, 27, 27)
                        .addComponent(btnListarF)
                        .addGap(18, 18, 18)
                        .addComponent(btnActualizarF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNomF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNomF, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(lblIdF)
                .addGap(26, 26, 26)
                .addComponent(txtIdF, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnRF, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnGuardarF)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminarF)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdF)
                    .addComponent(txtIdF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomF)
                    .addComponent(txtNomF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevaF, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnListarF)
                    .addComponent(btnActualizarF))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarF)
                    .addComponent(btnEliminarF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnRF, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        TablaFases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaFases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaFasesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaFases);

        lblBuscar.setText("Buscar:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 17, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarFActionPerformed
        insertarFases();
    }//GEN-LAST:event_btnGuardarFActionPerformed

    private void btnNuevaFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaFActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnNuevaFActionPerformed

    private void btnListarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFActionPerformed
        listarFases();
    }//GEN-LAST:event_btnListarFActionPerformed

    private void TablaFasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaFasesMouseClicked
        int filaSelec = TablaFases.rowAtPoint(evt.getPoint());
        
        txtIdF.setText(TablaFases.getValueAt(filaSelec,0).toString());
        txtNomF.setText(TablaFases.getValueAt(filaSelec,1).toString());
     
    }//GEN-LAST:event_TablaFasesMouseClicked

    private void btnEliminarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarFActionPerformed
       eliminarFases();
       listarFases();
       limpiarCampos();
    }//GEN-LAST:event_btnEliminarFActionPerformed

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        filtrarFases(txtBusqueda.getText());
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void btnRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRFActionPerformed
        Menu men =new Menu();
          men.setVisible(true);
          dispose();
    }//GEN-LAST:event_btnRFActionPerformed

    private void btnActualizarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarFActionPerformed
       actualizarFases();
       listarFases();
       limpiarCampos();
    }//GEN-LAST:event_btnActualizarFActionPerformed

    
     public void insertarFases() {

        try {
         
          String query = "insert into Fases (id_fase, nombreFase) values (?,?)";

            PreparedStatement pst = con.prepareStatement(query);
            pst.setInt(1, Integer.parseInt(txtIdF.getText()));
            pst.setString(2, txtNomF.getText());

            pst.execute();
            JOptionPane.showMessageDialog(null, "Registro Fases Guardado");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro Fases No Guardado" + e.getMessage());
        }
    }
     
     
      public void limpiarCampos(){
    txtIdF.setText("");
    txtNomF.setText("");
}
      
     public void listarFases(){
        String[] titulos ={"id_fase", "nombreFase"};
        String[] registros= new String[2];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        
        String query = "select * from Fases";
        try {
            Statement st =con.createStatement();
            ResultSet rs= st.executeQuery(query);
            
            while(rs.next()){
                registros[0]=rs.getString("id_fase");
                registros[1]=rs.getString("nombreFase");
                
                
                modelo.addRow(registros);                
            }
            
            TablaFases.setModel(modelo);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Error al listar Fases" + e.getMessage());       
        }   
    }
     
     public void eliminarFases(){
    int filaSelec =TablaFases.getSelectedRow();
    
        try {
            String query=" delete from Fases where id_fase="+TablaFases.getValueAt(filaSelec,0);
            
            Statement st=con.createStatement();
            
            int n=st.executeUpdate(query);
            
            if (n>=0){
             JOptionPane.showMessageDialog(null, "Registro Fases Eliminado");   
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro Fases No Eliminado" + e.getMessage()); 
        }
    
    }
     
      public void filtrarFases(String valor){
        String[] titulos ={"id_fase", "nombreFase"};
        String[] registros= new String[2];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        
        String query = "select * from Fases where nombrefase like '%"+ valor + "%' ";
        try {
            Statement st =con.createStatement();
            ResultSet rs= st.executeQuery(query);
            
            while(rs.next()){
                registros[0]=rs.getString("id_fase");
                registros[1]=rs.getString("nombreFase");
                
                
                modelo.addRow(registros);                
            }
            
            TablaFases.setModel(modelo);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Error al listar Fases" + e.getMessage());       
        }   
    }
      
       public void actualizarFases() {

        try {
         
          String query = "update Fases Set nombrefase=? where id_fase =?";

            int filaSelect=TablaFases.getSelectedRow();
          
            PreparedStatement pst = con.prepareStatement(query);
            
            pst.setString(1, txtNomF.getText());
            pst.setInt(2, Integer.parseInt(txtIdF.getText()));
                    
            pst.executeUpdate();
            pst.close();
            JOptionPane.showMessageDialog(null, "Registro Fases Actualizado");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro Fases No Actualizado" + e.getMessage());
        }
    }
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaFases;
    private javax.swing.JButton btnActualizarF;
    private javax.swing.JButton btnEliminarF;
    private javax.swing.JButton btnGuardarF;
    private javax.swing.JButton btnListarF;
    private javax.swing.JButton btnNuevaF;
    private javax.swing.JButton btnRF;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblIdF;
    private javax.swing.JLabel lblNomF;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtIdF;
    private javax.swing.JTextField txtNomF;
    // End of variables declaration//GEN-END:variables
}
