/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import conexionSQL.conexionSQL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class Metodologia extends javax.swing.JFrame {

    conexionSQL cc = new conexionSQL();
    Connection con = cc.conexion();
    
    public Metodologia() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtIdM = new javax.swing.JTextField();
        lblIdM = new javax.swing.JLabel();
        lblNomM = new javax.swing.JLabel();
        btbListarM = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMetodologias = new javax.swing.JTable();
        lblNoF = new javax.swing.JLabel();
        txtNunF = new javax.swing.JTextField();
        cbMetodologias = new javax.swing.JComboBox<>();
        btbNuevoM = new javax.swing.JButton();
        btnActualizarM = new javax.swing.JButton();
        btbEliminarM = new javax.swing.JButton();
        btbGuardarM = new javax.swing.JButton();
        lblBuscar = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnRM = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metodologia");

        lblIdM.setText("Id:");

        lblNomM.setText("Metodologia:");

        btbListarM.setText("Listar");
        btbListarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbListarMActionPerformed(evt);
            }
        });

        TablaMetodologias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaMetodologias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMetodologiasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaMetodologias);

        lblNoF.setText("No. Fases:");

        txtNunF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNunFActionPerformed(evt);
            }
        });

        cbMetodologias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RUP", "Scrum", "Cascada", "Agile", "Xp", "Prototipado", "Espiral" }));

        btbNuevoM.setText("Nuevo");
        btbNuevoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbNuevoMActionPerformed(evt);
            }
        });

        btnActualizarM.setText("Actualizar");
        btnActualizarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarMActionPerformed(evt);
            }
        });

        btbEliminarM.setText("Eliminar");
        btbEliminarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbEliminarMActionPerformed(evt);
            }
        });

        btbGuardarM.setText("Guardar");
        btbGuardarM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbGuardarMActionPerformed(evt);
            }
        });

        lblBuscar.setText("Buscar:");

        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        btnRM.setForeground(new java.awt.Color(204, 0, 0));
        btnRM.setText("Regresar");
        btnRM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblBuscar)
                                .addGap(18, 18, 18)
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRM, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNoF)
                                .addGap(18, 18, 18)
                                .addComponent(txtNunF, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(btbGuardarM)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblIdM)
                                .addGap(58, 58, 58)
                                .addComponent(txtIdM, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(94, 94, 94)
                                .addComponent(btbNuevoM)
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnActualizarM)
                                    .addComponent(btbEliminarM)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblNomM)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbMetodologias, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(btbListarM)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdM)
                            .addComponent(txtIdM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNomM)
                            .addComponent(cbMetodologias, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNunF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNoF)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btbNuevoM)
                            .addComponent(btnActualizarM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btbEliminarM)
                            .addComponent(btbListarM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btbGuardarM)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBuscar)
                            .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnRM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnActualizarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarMActionPerformed
       actualizarMetodologia();
       limpiarCampos();
       listarMetodologias();
    }//GEN-LAST:event_btnActualizarMActionPerformed

    private void txtNunFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNunFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNunFActionPerformed

    private void btbGuardarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbGuardarMActionPerformed
       insertarMetodologia();
    }//GEN-LAST:event_btbGuardarMActionPerformed

    private void btbNuevoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbNuevoMActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btbNuevoMActionPerformed

    private void btbListarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbListarMActionPerformed
        listarMetodologias();
    }//GEN-LAST:event_btbListarMActionPerformed

    private void btbEliminarMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbEliminarMActionPerformed
        eliminarMetodologias();
        listarMetodologias();
        limpiarCampos();
    }//GEN-LAST:event_btbEliminarMActionPerformed

    private void TablaMetodologiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMetodologiasMouseClicked
         int filaSelec = TablaMetodologias.rowAtPoint(evt.getPoint());
        
        txtIdM.setText(TablaMetodologias.getValueAt(filaSelec,0).toString());
        cbMetodologias.setSelectedItem(TablaMetodologias.getValueAt(filaSelec,1).toString());
        txtNunF.setText(TablaMetodologias.getValueAt(filaSelec,2).toString());
    }//GEN-LAST:event_TablaMetodologiasMouseClicked

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
        filtrarMetodologias(txtBusqueda.getText());
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void btnRMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRMActionPerformed
        Menu men =new Menu();
          men.setVisible(true);
          dispose();
    }//GEN-LAST:event_btnRMActionPerformed

    
    
    public void insertarMetodologia() {

        try {
         
          String query = "insert into Metodologia (id_metodologia, nombreMetodologia, numfase) values (?,?,?)";

            PreparedStatement pst = con.prepareStatement(query);
            pst.setInt(1, Integer.parseInt(txtIdM.getText()));
            
            int seleccionado=cbMetodologias.getSelectedIndex();
            pst.setString(2,cbMetodologias.getItemAt(seleccionado));
            pst.setInt(3, Integer.parseInt(txtNunF.getText()));

            pst.execute();
            JOptionPane.showMessageDialog(null, "Registro Metodologias Guardado");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro Metodologias No Guardado" + e.getMessage());
        }
    }
    
       public void limpiarCampos(){
    txtIdM.setText("");
    cbMetodologias.setSelectedItem(null);
    txtNunF.setText("");
}
      
     public void listarMetodologias(){
        String[] titulos ={"id_metodologia", "nombreMetodologia","numfase"};
        String[] registros= new String[3];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        
        String query = "select * from Metodologia";
        try {
            Statement st =con.createStatement();
            ResultSet rs= st.executeQuery(query);
            
            while(rs.next()){
                registros[0]=rs.getString("id_metodologia");
                registros[1]=rs.getString("nombreMetodologia");
                registros[2]=rs.getString("numfase");
                
                modelo.addRow(registros);                
            }
            
            TablaMetodologias.setModel(modelo);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Error al listar Metodologias" + e.getMessage());       
        }   
    }
     
     public void eliminarMetodologias(){
    int filaSelec =TablaMetodologias.getSelectedRow();
    
        try {
            String query=" delete from Metodologia where id_metodologia="+TablaMetodologias.getValueAt(filaSelec,0);
            
            Statement st=con.createStatement();
            
            int n=st.executeUpdate(query);
            
            if (n>=0){
             JOptionPane.showMessageDialog(null, "Registro Metodologias Eliminado");   
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro Metodologias No Eliminado" + e.getMessage()); 
        }
    
    }
     
     
     public void filtrarMetodologias(String valor){
        String[] titulos ={"id_metodologia", "nombreMetodologia","numfase"};
        String[] registros= new String[3];
        
        DefaultTableModel modelo = new DefaultTableModel(null,titulos);
        
        String query = "select * from Metodologia where nombreMetodologia like '%"+ valor + "%' ";
        try {
            Statement st =con.createStatement();
            ResultSet rs= st.executeQuery(query);
            
            while(rs.next()){
                registros[0]=rs.getString("id_metodologia");
                registros[1]=rs.getString("nombreMetodologia");
                registros[2]=rs.getString("numfase");
                
                modelo.addRow(registros);                
            }
            
            TablaMetodologias.setModel(modelo);
        } catch (Exception e) {
           JOptionPane.showMessageDialog(null, "Error al filtrar Metodologias" + e.getMessage());       
        }   
     }    
     
     public void actualizarMetodologia() {

        try {
         
          String query = "update Metodologia Set nombreMetodologia=?, numfase=? where id_metodologia =?";

            int filaSelect=TablaMetodologias.getSelectedRow();
          
            PreparedStatement pst = con.prepareStatement(query);
            
            int seleccionado=cbMetodologias.getSelectedIndex();
            pst.setString(1,cbMetodologias.getItemAt(seleccionado));
            pst.setInt(2, Integer.parseInt(txtNunF.getText()));
            pst.setInt(3, Integer.parseInt(txtIdM.getText()));
                    
            pst.executeUpdate();
            pst.close();
            JOptionPane.showMessageDialog(null, "Registro Metodologia Actualizado");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Registro Metodologia No Actualizado" + e.getMessage());
        }
    }
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Metodologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Metodologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Metodologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Metodologia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Metodologia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaMetodologias;
    private javax.swing.JButton btbEliminarM;
    private javax.swing.JButton btbGuardarM;
    private javax.swing.JButton btbListarM;
    private javax.swing.JButton btbNuevoM;
    private javax.swing.JButton btnActualizarM;
    private javax.swing.JButton btnRM;
    private javax.swing.JComboBox<String> cbMetodologias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblIdM;
    private javax.swing.JLabel lblNoF;
    private javax.swing.JLabel lblNomM;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtIdM;
    private javax.swing.JTextField txtNunF;
    // End of variables declaration//GEN-END:variables
}
